# Generated by Django 2.0.3 on 2018-10-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default='trying'),
            preserve_default=False,
        ),
    ]
